### PR TITLE
add new period 'paper'

### PR DESCRIPTION
**Pull request by Jovi-Wong**
Graduation paper of this period needs to be submitted onto official website individually

### CODE REVIEW

**Comment by TheNetAdmin** [comment]
Is there any specific requirements of 'paper' period that are different from the current ones?

**Comment by TheNetAdmin** [comment]
Oh I see what you mean. In the 'paper' period, you just want the final paper part, without the proposal part, am I right?

**Comment by Jovi-Wong** [comment]
yeah，it is also required by zju

**Comment by TheNetAdmin** [comment]
Merged, thank you for the PR! Wish you the best of luck with your graduation.

**Comment by Asudy** [comment]
@TheNetAdmin 我之前使用8.5.0版本配置并已经完成了一部分文字，请问是否用新的 `zjuthesis.tex` 覆盖原有的改文件就可以正常使用新的 'paper' period 功能？

**Comment by TheNetAdmin** [comment]
对

**Comment by Asudy** [comment]
> 对

谢谢！

**Pull request merged**
